name: Deploy to Developer Portal PROD Bucket
permissions: {}

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy-to-developer-portal-prod.yml"
      - "docusaurus/**"
      - "docs/**"
jobs:
  deploy:
    name: Deploy docs to Developer Portal Bucket
    runs-on: ubuntu-latest
    permissions:
      contents: read #Clone repo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable --prefer-offline
      
        #mac: sed -i '' '1s/^/---\nslug: \/\n---\n/' ./docs/contract/contract.md
        #linux: sed -i '1s/^/---\nslug: \/\n---\n/' ./docs/contract/contract.md
      - name: Make docs the homepage of this subsite
        run: |
          rm -f ./docusaurus/website/src/pages/index.tsx
          sed -i '1s/^/---\nslug: \/\n---\n/' ./docs/contract/contract.md
            
      - name: Build documentation website
        run: yarn docs:build:devportal:prod
          
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
       
      - name: 'Deploy to Developer Portal Bucket'
        run: |
          gsutil -m rsync -r -d -c ./docusaurus/website/build/ gs://grafana-developer-portal/dataplane