name: Deploy to Developer Portal DEV Bucket
permissions: {}

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Which branch to use?"
        default: "main"
jobs:
  deploy:
    name: Deploy docs to Developer Portal Bucket
    runs-on: ubuntu-latest
    permissions:
      contents: read #Clone repo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable --prefer-offline
      
      - name: Make docs the homepage of this subsite
        run: |
          rm -f ./docusaurus/website/src/pages/index.tsx
          sed -i '1s/^/---\nslug: \/\n---\n/' ./docs/contract/contract.md
            
      - name: Build documentation website
        run: yarn docs:build:devportal:dev
          
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_DEV }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
       
      - name: 'Deploy to Developer Portal Bucket'
        run: |
          gsutil -m rsync -r -d -c ./docusaurus/website/build/ gs://staging-developer-portal/dataplane