name: E2E
on:
  pull_request:
    paths:
      - e2e/**
      - .github/workflows/e2e.yml
  push:
    branches:
      - main
    paths:
      - e2e/**
      - .github/workflows/e2e.yml
  schedule:
    - cron: "30 8,18 * * *"
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  e2e:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        gfVersion: ["8.4.7", "latest", "main"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: NodeJS Setup
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
      - name: Install dependencies
        run: cd e2e && yarn install --frozen-lockfile;
      - name: Start the docker container for e2e
        run: cd e2e && docker-compose pull && docker-compose up -d
        env:
          GF_VERSION: ${{ matrix.gfVersion }}
          GF_ENTERPRISE_LICENSE_TEXT: ${{ secrets.GF_ENTERPRISE_LICENSE_TEXT }}
      - name: Wait for grafana to start
        uses: nev7n/wait_for_response@v1
        with:
          url: "http://localhost:3000/"
          responseCode: 200
          timeout: 600000
          interval: 500
      - name: Run E2E
        run: cd e2e && yarn e2e
      - name: Stop the docker container
        if: always()
        run: cd e2e && docker-compose down
      - name: Store E2E artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: e2e-artifacts-${{ matrix.gfVersion }}
          path: |
            e2e/cypress/videos
            e2e/cypress/screenshots
